version: "3.8"
services:
  web:
    build: .
    container_name: flask_web
    env_file: .env
    volumes:
      - ./uploads:/app/uploads
    expose:
      - "5000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always
